config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  devise_for :users
  root to: 'recipes#index'
  get "general_shopping_list", to: 'shopping_list#index'
  get "public_recipes", to: 'public_recipe#index'

end

app/views/navbar/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiar navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Recipes App', recipes_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-between" style="width: 100%;">
        <div class="d-flex">
        <li class="nav-item">
          <%= link_to "recipes", recipes_path, class: "nav-link whiten" %>
        </li>
        <li class="nav-item">
          <%= link_to "Food", foods_path, class: "nav-link whiten" %>
        </li>
        <li class="nav-item">
          <%= link_to "public recipes", public_recipes_path, class: "nav-link whiten" %>
        </li>
        <li class="nav-item">
          <%= link_to "Shopping list", general_shopping_list_path, class: "nav-link whiten" %>
        </li>
        </div>
        <div class="d-flex">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link whiten" %>
        </li>
        <li class="nav-item">
        <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link whiten" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign in", new_user_session_path, class: "nav-link whiten" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link whiten" %>
        </li>
        <% end %>
        </div>
      </ul>
    </div>
  </div>
</nav>