config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  devise_for :users
  root to: 'recipes#index'
  get "general_shopping_list", to: 'shopping_list#index'
  get "public_recipes", to: 'public_recipe#index'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
  validates :name, presence: true, length: { maximum: 50 }
  # validates :measurement_unit, presence: true
  # validates :name, :preparation_time, :cooking_time, :discription, presence: true
  # validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  helper_method :calculate_total_price
  before_action :set_recipe, only: %i[show edit update destroy new_food create_food]

  def public_recipes
    @public_recipes = Recipe.where(public: true).order(created_at: :desc).includes(:recipe_foods)
  end

  def show
    @recipe = Recipe.includes(:foods, :recipe_foods).find(params[:id])
  end

  def toggle_visibility
    @recipe.update(is_public: !@recipe.is_public)
    redirect_to @recipe, notice: 'Recipe visibility updated.'
  end

  def destroy
    if @recipe.user != current_user
      redirect_to @recipe, alert: 'You are not authorized to perform this action.'
      return
    end

    filtered_recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    filtered_recipe_foods.destroy_all
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    @recipes = Recipe.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully added.'
    else
      render :new
    end
  end

  def new_food
    @current_user = current_user
    if @recipe.user_id != current_user.id
      redirect_to recipe_url(@recipe), alert: 'You donot have the authority to modify that recipe!.'
    end
    @food = Food.new
  end

  def create_food
    # @food = Food.new(food_params)
    @food = @recipe.foods.new(food_params)
    @food.recipe_id = @recipe.id
    @food.user_id = @recipe.user_id

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully added to the recipe.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :discription, :public, :user_id)
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id, :recipe_id)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time %> <span>(in minutes)</span>
    <br>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time %> <span>(in minutes)</span>
    <br>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <h1 style="text-align:center;text-transform: capitalize;"><%= recipe.name %></h1>
  <div class="d-flex justify-content-between">
    <p>
      <strong>Preparation time:</strong>
      <%= recipe.preparation_time %> minutes
    </p>
    <% if current_user.present? && recipe.user_id == current_user.id %>
    <%= form_with(model: recipe) do |form| %>
        <div class="form-check form-switch ">
            <%= form.check_box :public, class: "form-check-input", onchange: "this.form.submit();" %>
            <%= form.label :public, class: "form-check-label", style: "display: block" %>
        </div>
    <% end %>
    <% end %>
  </div>
  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %> minutes
  </p>

  <p>
    <%= recipe.discription %>
  </p>

</div>

app/views/recipes/_toggle_visibility_button.html.erb
<% if current_user == @recipe.user %>
  <div class="toggle-visibility-button">
    <input type="checkbox" id="toggle-public" <%= @recipe.public ? 'checked' : '' %> data-recipe-id="<%= @recipe.id %>">
    <label for="toggle-public" class="toggle-label"></label>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="d-flex flex-column align-items-center">
  <h1>My Recipes</h1>
  <br>
  <div class='new-recipe-btn'>
  <%= link_to "New Recipe", new_recipe_path, class: "btn btn-primary" %> 
  </div>
  <br>
  <div id="recipes">
    <% @recipes.each do |recipe| %>
        <div class="card mb-3 p-4" style="max-width: 700px;" onclick="redirectFunction(<%= recipe.id %>)">
        <div class="row g-0">
          <div class="col-md-4">
            <h5 class="card-title"><%= recipe.name %></h5>
            <%= button_to "Remove", recipe, method: :delete, class: "button-to-link" %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <p class="card-text"><%= recipe.discription %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= link_to "New recipe", new_recipe_path %>
  </div>
</div>
<script>
function redirectFunction(id) {
  window.location.href += `/${id}`;
}
</script>

app/views/recipes/new.html.erb
<h2>New recipe</h2>

<%= render "form", recipe: @recipe %>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipes</h1>

<ul class="recipe-list">
  <% @public_recipes.each do |recipe| %>
    <li class="recipe-item">
      <%= link_to recipe_path(recipe.id), class: 'recipe-link' do %>
        <div class="recipe-details">
          <h4><%= recipe.name %></h4>
          <p><strong>By:</strong> <%= recipe.user.name %></p>
        </div>
        <div class="recipe-stats">
          <p><strong>Total Food Items:</strong> <%= recipe.recipe_foods.count %></p>
          <p><strong>Total Price:</strong> <%= recipe.recipe_foods.sum(&:total_price) %></p>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/recipes/show.html.erb
<% if current_user == @recipe.user || @recipe.public %>
  <!-- Display recipe details -->
  <%= render @recipe %>
  <% if current_user.present? && @recipe.user_id == current_user.id %>
    <div class="show-links">
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
      <%= link_to "Back to recipes", recipes_path %> |
      <%= button_to "Destroy this recipe", @recipe, method: :delete, class: "button-to-link"%>
    </div>
    <br>
    <div class="buttons-group d-flex justify-content-between">
      <%= link_to "Generate shopping list", general_shopping_list_path, class:"btn btn-primary" %>
      <%= link_to "Add ingredient", new_recipe_recipe_food_url(@recipe), class:"btn btn-primary" %>
    </div>
    <hr>
    <% filtered_recipe_foods = RecipeFood.where(recipe_id: @recipe.id)%>
    <table id="recipe-ingredients" class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Food</th>
          <th scope="col">Total price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Show this food</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% filtered_recipe_foods.each_with_index do |filtered_recipe_food, index| %>
          <% food = Food.find(filtered_recipe_food.food_id) %>
          <% recipe = Recipe.find(filtered_recipe_food.recipe_id) %>
          <tr id="<%= dom_id food %>">
            <th scope="row"><%= index + 1 %></th>
            <td><%= food.name %></td>
            <td><%= food.price * filtered_recipe_food.quantity %> $</td>
            <td><%= food.quantity * filtered_recipe_food.quantity %> <%= food.measurement_unit %></td>
            <td>
              <%= link_to "link", food %>
            </td>
            <td>
              <%= link_to "Modify", edit_recipe_recipe_food_path(recipe, filtered_recipe_food.id) %> |
              <%= button_to "Remove", recipe_recipe_food_url(recipe, filtered_recipe_food.id), method: :delete, class: "button-to-link" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%= link_to "Back to recipes", recipes_path %>
  <% end %>
<% end %>