config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  devise_for :users
  root to: 'recipes#index'
  get "general_shopping_list", to: 'shopping_list#index'
  get "public_recipes", to: 'public_recipe#index'

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  validates :name, presence: true, length: { maximum: 50 }
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show
    @recipe_foods = @food.recipe_foods.includes(:recipe)
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    # @food = Food.new(food_params)
    @current_user = current_user
    @food = @current_user.foods.new(food_params)
    @food.user_id = @current_user.id
    food_name_test = Food.find_by(name: @food.name, user_id: @food.user_id)
    if food_name_test
      redirect_to new_food_path, alert: 'couldnot create this food as its name is already exisiting in your food list'
    else
      respond_to do |format|
        if @food.save
          format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
          format.json { render :show, status: :created, location: @food }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @food.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    filtered_recipe_foods = RecipeFood.find_by(food_id: @food.id)
    if filtered_recipe_foods
      redirect_to foods_url, alert: 'Cannot destroy this food cause it is contained in one of your recipes'
    else
      @food.destroy
      respond_to do |format|
        format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = current_user.foods.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price %><span> in $</span>
    <br>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/add.html.erb
<h2>Add a new food</h2>

<%= form_with(model: Food.new, url: foods_path, method: :post, html: { class: "foods-form" }) do |form| %>

<%= form.label :name %>
<%= form.text_field :name %>

<%= form.submit "Add new food" %>

<% end %>

app/views/foods/index.html.erb
<h1>Foods</h1>

<div class='food-container'>
<div class='new-food-btn'>
<%= link_to "New Food", new_food_path, class: "btn btn-primary" %> 
</div>
<div>
<table id="foods" class="table table-bordered">
  <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Show this food</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
  <% @foods.each_with_index do |food, index| %>
  <tr id="<%= dom_id food %>">
    <th scope="row"><%= index + 1 %></th>
    <td><%= food.name %></td>
    <td><%= food.measurement_unit %></td>
    <td><%= food.price %> $</td>
    <td><%= food.quantity %></td>
    <td>
      <%= link_to "link", food %>
    </td>
    <td>
      <%= button_to "Delete", food, method: :delete, class: "button-to-link" %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>

</div>

app/views/foods/new.html.erb
<h2>Add New Food</h2>

<%= render 'form', food: @food %>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete  %>
</div>