config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  devise_for :users
  root to: 'recipes#index'
  get "general_shopping_list", to: 'shopping_list#index'
  get "public_recipes", to: 'public_recipe#index'

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe_food, only: %i[show edit update destroy]

  def index
    #     @recipe = Recipe.find(params[:recipe_id])
    #     redirect_to @recipe
    @recipe_foods = current_user.recipe_foods.includes(:food, :recipe)
    @total_items = @recipe_foods.sum(:quantity)
    @total_price = @recipe_foods.sum { |item| item.quantity * item.food.price }
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show
    @recipe = Recipe.find(params[:recipe_id])
  end

  # GET /recipe_foods/new
  def new
    @recipe = Recipe.find(params[:recipe_id])
    if @recipe.user_id != current_user.id
      redirect_to recipe_url(@recipe), alert: 'You donot have the authority to modify that recipe!.'
    end
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit
    @recipe = Recipe.find(params[:recipe_id])
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = @recipe.id
    food_id_test = RecipeFood.find_by(recipe_id: @recipe_food.recipe_id, food_id: @recipe_food.food_id)
    if food_id_test
      redirect_to @recipe, alert: 'Recipe food ingredient already existed in your recipe food list!.'
    else
      respond_to do |format|
        if @recipe_food.save
          format.html { redirect_to @recipe, notice: 'Recipe food ingredient was successfully added.' }
          format.json { render :show, status: :created, location: @recipe_food }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    @recipe = Recipe.find(params[:recipe_id])
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to @recipe, notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to @recipe, notice: 'Recipe food ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food, url: recipe_recipe_foods_url(params[:recipe_id])) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <% options = [] %>
  <% Food.where(user_id: current_user.id).each do |food|%>
    <% option = [ food.name, food.id ]%>
    <% options.push(option) %>
  <% end %>
  <div>
    <%= form.label :food_id, style: "display: block" %>
    <%= form.select :food_id, options_for_select(options), prompt: 'Select an option' %>
  </div>

  <br>
  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipe_foods/index.html.erb
<h1>Shopping List</h1>

<p>Total food items to buy: <%= @total_items %></p>
<p>Total value of food needed: <%= number_to_currency(@total_price) %></p>

<h2>Missing Ingredients:</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price per unit</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_foods.each do |item| %>
      <tr>
        <td><%= item.food.name %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.food.price) %></td>
        <td><%= number_to_currency(item.quantity * item.food.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>